---
- name: Health-Check Application and Database
  hosts: web
  become: true
  vars:
    base_url: "http://localhost:9090"
  tasks:
    - name: Check application endpoint
      uri:
        url: "{{ base_url }}/"
        method: GET
        status_code: 200
- name: Wait for MySQL to accept connections
      wait_for:
        host: localhost
        port: 3306
        state: started
        timeout: 30
